project:
  type: website
  output-dir: docs
  resources: CNAME
  
website:
  title: "European Bioconductor Conference 2025"
  navbar:
    toggle-position: right
    logo: images/logoBioc.svg
    logo-alt: "Bioconductor"
    title: false
    collapse-below: lg
    right:
      - href: pages/schedule.qmd
      - href: pages/speakers.qmd
      - href: pages/submissions.qmd
      - href: pages/registration.qmd
      - href: pages/sponsors.qmd
      - text: About
        menu:
          - href: pages/organizers.qmd
          - href: pages/past-events.qmd
          - href: pages/code-of-conduct.qmd
          - href: pages/travel-information.qmd
  page-footer:
    left: |
      [![](../images/logoUPF.png){width=30%}](https://www.upf.edu/biomed)
      [![](../images/logoISGLOBAL.png){width=30%}](https://www.isglobal.org)
      [![](../images/logoPRBB.png){width=30%}](https://prbb.org)
    center: |
      Copyright &copy; 2024 Bioconductor
      [Code of Conduct](https://www.bioconductor.org/about/code-of-conduct)
      <br>contact: [eurobioc@bioconductor.org](mailto:eurobioc@bioconductor.org)
    right:
      - href: https://github.com/Bioconductor/EuroBioC2025
        icon: github
        aria-label: GitHub
      - href: https://bsky.app/profile/bioconductor.bsky.social
        text: |
          [![](../images/logoBluesky.png){fig-alt="Bluesky" height=15px}
          ](https://bsky.app/profile/bioconductor.bsky.social)
        aria-label: Bluesky
      - href: https://genomic.social/@bioconductor
        icon: mastodon
        aria-label: Mastodon
      - href: https://www.linkedin.com/company/bioconductor
        icon: linkedin
        aria-label: LinkedIn
      - href: https://slack.bioconductor.org
        icon: slack
        aria-label: Slack
   
page-navigation: true
back-to-top-navigation: false

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px
