project:
  type: website
  output-dir: docs
  
website:
  title: "European Bioconductor Conference 2025"
  navbar:
    toggle-position: right
    logo: images/bioclogo.svg
    logo-alt: "Bioconductor"
    title: false
    collapse-below: lg
    right:
      - href: pages/schedule.qmd
      - href: pages/speakers.qmd
      - href: pages/submissions.qmd
      - href: pages/registration.qmd
      - href: pages/sponsors.qmd
      - text: About
        menu:
          - href: pages/organizers.qmd
          - href: pages/past-events.qmd
          - href: pages/code-of-conduct.qmd
          - href: pages/travel-information.qmd

page-navigation: true

back-to-top-navigation: false

page-footer:
  background: "#000000"
  left: |
    [Copyright &copy; 2024 Bioconductor](/LICENCE.md)
  center:
    - href: https://github.com/Bioconductor/EuroBioC2025
      icon: github
      aria-label: GitHub
    - href: https://genomic.social/@bioconductor
      icon: mastodon
      aria-label: Mastodon
    - href: https://www.linkedin.com/company/bioconductor
      icon: linkedin
      aria-label: LinkedIn
    - href: https://slack.bioconductor.org
      icon: slack
      aria-label: Slack

  right: |
    [Code of Conduct](https://www.bioconductor.org/about/code-of-conduct)

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px
