# Conference dinner

The registration to EuroBioC2025 includes a conference dinner in cocktail format
on Wednesday 17th
at 20:00 hrs at the [Old Hospital de Sant Pau](https://santpaubarcelona.org/en){target="_blank"},
a former hospital complex and now a
[UNESCO World Heritage site](https://whc.unesco.org/en/list/804){target="_blank"},
concretely in the room called
["Domènech i Montaner"](https://santpaubarcelona.org/en/lloguer/sala-lluis-domenech-i-montaner){target="_blank"},
after the name of the architect of the building. This site is about 4km away from
the conference venue, its specific address is:

**Old Hospital de Sant Pau**  
Carrer de Sant Antoni Maria Claret, 167  
08025 Barcelona  
(see [Google directions](https://maps.app.goo.gl/o3iQe1oQfjWPxVwm9){target="_blank"})  

The four main options to reach it from the conference venue are:

* **Walking (~1 hr uphill)**
  (see [Google directions](https://maps.app.goo.gl/3E7atKv9oPsVocAo7){target="_blank"}).
* **By bus (~40 minutes).** Taking the bus
  [V21](https://www.tmb.cat/en/barcelona/buses/-/lineabus/V21){target="_blank"}
  starting at the stop on the corner between Trelawny and Passeig Marítim, at the
  seafront, and stepping out ten stops later at Padilla with Indústria. From
  that stop, it is a 5-minute walk going uphill to Sant Antoni Maria Claret, and
  going right till the corner of this street with Carrer Cartegena (see
  [Google directions](https://maps.app.goo.gl/F7LrejShzpUtyFJ58){target="_blank"}).

* **By subway (~35 minutes).** Taking the
  [L4 (yellow) line](https://www.tmb.cat/en/barcelona/metro/-/lineametro/L4){target="_blank"}
  direction Trinitat Nova, starting at the stop Ciutadella - Vila Olímpica, which
  is about 10 minutes walking from the conference venue, stepping out 6 stops
  later in Verdaguer, and switching to the
  [L5 (blue) line](https://www.tmb.cat/en/barcelona/metro/-/lineametro/L5){target="_blank"} direction
  Vall d'Hebron, and stepping out two stops later in Sant Pau | Dos de Maig. From there
  it is a 5 minute walk uphill through Cartagena until you meet the main entrance
  (see [Google directions](https://maps.app.goo.gl/TJ5EwcYDzwYYBGbH8){target="_blank"}).
* **By taxi (~20 minutes).** There is a taxi stop right in front of the PRBB
  building. Taxi rides apps that usually work well in Barcelona are
  [FreeNow](https://www.free-now.com/es-en){target="_blank"} and
  [Cabify](https://cabify.com/en){target="_blank"}.
