# Registration

## Fees

| Type                                                                  |   Fee    |
|:----------------------------------------------------------------------|:--------:|
|Student (undergraduate, master or PhD students)                        | **€150** |
|Academic (researchers from academic and other non-profit institutions) | **€325** |
|Industry (employees from corporate for-profit organizations)           | **€600** |

The registration fee includes coffee breaks between sessions, snacks and drinks during
poster sessions, lunch on Wednesday and Thursday, and a conference dinner on Wednesday.
Please do not forget to fill out in the registration form your dietary restrictions and
whether you will be attending the conference dinner.

## Cancellation policy

The budget EuroBioC2025 is conceived to break even after the conference. As a
result, the organization of the EuroBioC2025 is unable to offer individual refunds.

## Register

**Registration for EuroBioC2025 is now open at
[https://eventum.upf.edu/go/eurobioc2025](https://eventum.upf.edu/go/eurobioc2025){target="_blank"}**.

**Important:** If you need an invoice to order the payment by bank transfer or
to get the registration fee reimbursed by your employer, please fill out the
invoicing information details in the corresponding text box of the registration form.
Note that the online registration system **does not** automatically generate invoices
and it may take us a few days or weeks to prepare and send you the invoice.

After the conference, we will provide certificates of attendance. For further
inquiries related to conference registration, please contact us at
[eurobioc@bioconductor.org](mailto:eurobioc@bioconductor.org).

## Travel and accommodation

Please consult the page on [travel information](travel-information.qmd)
