# Travel Information

## How to get to Barcelona

You can get to Barcelona in the following ways:

* **By train:** Barcelona is connected with high-speed trains with France and
  Madrid as well as other cities in Spain. The main railway station where high-speed
  trains arrive is
  [Barcelona-Sants](https://www.barcelona.cat/en/discoverbcn/pics/la-estacion-de-sants-92086009180).
  Barcelona is also the hub of the regional and metropolitan train network of
  Catalonia; see
  [Rodalies de Catalunya](https://rodalies.gencat.cat/en/horaris/index.html) and
  [Ferrocarrils de la Generalitat](https://www.fgc.cat/en).

* **By plane:** The main international airport of Barcelona is
  [Josep Tarradellas (BCN)](https://www.aeropuertobarcelona-elprat.com/ingl/index.html),
  formerly known as "El Prat Airport", located about 16 Km away from the south of the
  city. You can reach the city by a
  [shuttle bus](https://aerobusbarcelona.es/?lang=en),
  [subway (L9 South)](https://www.tmb.cat/en/visit-barcelona/public-transport/metro-airport)
  or [taxi](https://www.aeropuertobarcelona-elprat.com/ingl/barcelona_airport_taxis.htm). The regional airports of
  [Girona Costa-Brava (GRO)](https://www.aena.es/en/girona-costa-brava.html) and
  [Reus (REU)](https://www.aena.es/en/reus.html) are located about one hour away
  from the city.

* **By bus:** The main bus station with national and international services is
  the [Barcelona Nord Bus Station](https://barcelonanord.barcelona/en), but there
  are also bus services arriving to 
  [Barcelona-Sants](https://www.barcelona.cat/en/discoverbcn/pics/la-estacion-de-sants-92086009180)
  and other parts of the city.

* **By boat:** There are national and international connections by ferry to
  some of the most important cities in the Meditarranean at the
  [The Port of Barcelona](https://www.portdebarcelona.cat/en/business-and-services/traffic-and-goods/ferries).

* **By car:** Barcelona is connected by different motor highways, but bear in
  mind that access is restricted for polluting vehicles; see the
  [Barcelona Ring Roads Low Emission Zone](https://ajuntament.barcelona.cat/qualitataire/en/low-emission-zone/what-barcelona-ring-roads-low-emission-zone)
  and traffic jams are common during rush hours. There is a
  [Car Park Network](https://aparcamentsbsm.cat/en) of the city, as well as many
  other private parking facilities, but in general parking is expensive.

## Conference venue

The European Bioconductor Conference 2025 will take place at the
Barcelona Biomedical Research Park ([PRBB](https://prbb.org)).

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5986.9755460835695!2d2.1940969999999997!3d41.3852123!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12a4a306002af6a7%3A0x19d613601960f62c!2sBarcelona%20Biomedical%20Research%20Park%2C%20Ciutat%20Vella%2C%2008003%20Barcelona!5e0!3m2!1sen!2ses!4v1731921465451!5m2!1sen!2ses" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

The PRBB can be reached by:

* Subway, where the closest stop is "Ciutadella - Vila Olímpica" of the
[L4 (yellow) line](https://www.tmb.cat/en/barcelona/metro/-/lineametro/L4).

* Tram, where the closest stop is also called "Ciutadella - Vila Olímpica"
  of the [T6 tram line](https://www.tram.cat/en/lines-and-timetables).

* Bus, where the closest stops are "Trelawny - Av Litoral"
  ([D20](https://www.tmb.cat/en/barcelona/buses/-/lineabus/D20))
  and "Hospital del Mar"
  ([47](https://www.tmb.cat/en/barcelona/buses/-/lineabus/47),
  [59](https://www.tmb.cat/en/barcelona/buses/-/lineabus/59)
  and
  [D20](https://www.tmb.cat/en/barcelona/buses/-/lineabus/D20)).

### Breastfeeding

The PRBB has a room for breastfeeding. Please contact the organisation upon
registration during the conference for more information.

## Accommodation

Participants are responsible for their accommodation arrangements. While
Barcelona offers a wide range of possibilities for accommodation in terms of
standards and rates, it also receives many visitors for tourism and business,
which makes accommodation in Barcelona increasingly expensive every year. For
this reason, we recommend to explore different options and book as early as
possible. The following is a list of hotels located within 30 minutes walking
of the conference venue (in alphabetic order):

* [Hotel Acta Voraport](https://www.hotelvoraport.com/en) ([directions](https://maps.app.goo.gl/x9DqeiVjoGqLmVJ17))

* [Hotel Catalonia Born](https://www.cataloniahotels.com/es/hotel/catalonia-born) ([directions](https://maps.app.goo.gl/65Xs1bGhskg1JN9r8))

* [Hotel H10 Marina Barcelona](https://www.h10hotels.com/en/barcelona-hotels/h10-marina-barcelona) ([directions](https://maps.app.goo.gl/ef8eirTvZjT3mJDk9))

* [Hotel Motel One Barcelona-Ciutadella](https://www.motel-one.com/en/hotels/barcelona/hotel-barcelona-ciutadella) ([directions](https://maps.app.goo.gl/jVdRqQYM6en1eyRF9))

* [Hotel NH Barcelona Diagonal Center](https://www.nh-hotels.com/en/hotel/nh-barcelona-diagonal-center) ([directions](https://maps.app.goo.gl/9tAcTJiNnkDLR3BKA))

* [Hotel SB Icaria Barcelona](https://www.hotelicariabarcelona.com/en) ([directions](https://maps.app.goo.gl/Px1QaS7CbX86FQwA7))

Barcelona has an extensive subway and bus network, and to a less extent tram,
which allows one to quicky reach the conference venue from the other side of
the city in about 30 to 40 minutes, where you may be able to find cheaper
accommodation rates. Some of the city districts and quarters away from the
conference venue where you may enjoy your stay are:

* [Barri de Sants](https://g.co/kgs/avQnWa3)

* [Barri de Sant Antoni](https://g.co/kgs/HEViwSQ)

* [Eixample Esquerra](https://g.co/kgs/1VbS8iZ)

* [Eixample Dreta](https://g.co/kgs/krNjeiv)

* [Gràcia](https://g.co/kgs/bjMXG6Y)

* [Poble Sec](https://g.co/kgs/krZCZNS)

* [Poble Nou](https://g.co/kgs/WoPPbfB)

The [Resa Inn](https://www.resainn.com/accommodation/barcelona) network of
university residence halls may offer daily rates in some of their
student dorms in Barcelona (the one called "Campus del Mar" is very close to
the conference venue).

Barcelona also has quite a few youth hostels, which may offer some of the
lowest accommodation rates:

* [Hostelling International affiliated youth hostels](https://hihostels.com/hostels/?adventure=&country=Spain&city=Catalonia+-+Barcelona+-+City)

* [HostelWorld affiliated youth hostels](https://www.hostelworld.com/hostels/europe/spain/barcelona)

## Traveling with children

The official website of the tourist office of Barcelona,
[BarcelonaTurisme](https://www.barcelonaturisme.com/wv3/en/page/40/with-the-family.html){target="_blank"}
has information on activities to do with children. The conference venue
is only 10 minutes walking from the [Barcelona Zoo](https://zoobarcelona.cat/en){target="_blank"},
and 20 minutes from the [Barcelona Aquarium](https://aquariumbcn.com/en){target="_blank"}.

### Childcare services

The kindergarten [Chiqui La Vila](https://chiquilavila.org/en){target="_blank"}
is also about 10 minutes walking from the conference venue, and offers
babysitting services during the conference at the participant's expense. While
they accept children from all ages, their premises are more suitable for
children under 7 years of age. You may find more information in the following
[document](ChildcareEuroBioC2025_ChiquiLaVila.pdf){target="_blank"}. If you are
interested, please contact them at
[info@chiquilavila.org](mailto:info@chiquilavila.org) before
September 11th, 2025.

The following childcare services work on hourly basis and can give service
at the hotel or appartment where you are staying:
[https://nanniesbarcelona.com](https://nanniesbarcelona.com){target="_blank"} and
[https://nanniesmannies.com](https://nanniesmannies.com){target="_blank"}.

Please note that while all these childcare services are reputable businesses
in Barcelona, the Universitat Pompeu Fabra and Bioconductor cannot be held
responsible for any agreements that the participants of the conference reach
directly with them.
